### ISSUE TITLE
Works only with english windows

### ISSUE THREAD

**Issue by JanHanckel** [falahati/NVIDIASurroundToggler#2]
Hi,

I love your tool but sadly it only work with an english version of windows.

Normally I use my german windows and nothing happens on toggle, just an error message i can't remember. If I switch the windows language to engish everything works fine.

Could you please change it, to work with other languages as well?

My Windows: Windows 10 64-bit

**Comment by falahati** [comment]
Hi,
Could you give me the exact error message? And a screen shot from nVidia Control Panel while you are in surround tab.

Thanks

**Comment by JanHanckel** [comment]
Error when nvidia control panel is not opened: ![image](https://cloud.githubusercontent.com/assets/16724520/12372771/d2fe0b7c-bc62-11e5-8676-e4102b11ddcf.png)

Error when nvidia control panel is open:
![image](https://cloud.githubusercontent.com/assets/16724520/12372788/5f870170-bc63-11e5-8fb6-28d32d9c7e8c.png)

This is what your options say:
![image](https://cloud.githubusercontent.com/assets/16724520/12372793/8d600e8e-bc63-11e5-84cf-86dcf39f43c1.png)

nVidia Control Panel:
![image](https://cloud.githubusercontent.com/assets/16724520/12372777/0eefa94c-bc63-11e5-9c99-9d03eaef3fcc.png)

If you need more information, just tell me :-)

**Comment by Ensi-Ferrum** [comment]
In Surround.cs:

```
//var setupDialog = Utility.DefaultOnException(() => application.GetWindow("NVIDIA Set Up Surround"));
  var setupDialog = Utility.DefaultOnException(() => application.GetWindow("NVIDIA Surround einrichten"));

```

```
//|| enableButton.Text.ToLower().Contains("Disable".ToLower());
  || enableButton.Text.ToLower().Contains("Deaktivieren".ToLower());

```

```
// if (enableButton.Text.ToLower().Contains("Disable".ToLower()))
  if (enableButton.Text.ToLower().Contains("Deaktivieren".ToLower()))

```

**Comment by Tomblarom** [comment]
**EDIT:** I had to add ["NVIDIA Systemsteuerung"](https://i.imgur.com/k3CKdEQ.png) but the error is still there:
![img](https://i.imgur.com/KTVkgTw.png)

**Hey Ensi-Ferrum!** I made these customisations but the problem is still existing:
![img](https://i.imgur.com/ud8r3XS.png)

I installed Microsoft Visual Studio 2015 Enterprise and updated the libs:
![img](https://i.imgur.com/QLyK8P9.png)

In Surround.cs I made the suggested changes:
![img](https://i.imgur.com/owfLAyn.png)
..
![img](https://i.imgur.com/Q6kcYGm.png)
..
![img](https://i.imgur.com/iiclgMc.png)

**Comment by falahati** [comment]
I will take a look and try to add the german language. Just give me the pharases. Tnx

**Comment by falahati** [comment]
New version support Deutsch, download from releases page.
Each language needs only three phrases. If any one helps me get those, I can add them to the next version.
